### ISSUE TITLE
eval_data and MappingNode with a tag different from 'tag:yaml.org,2002:str'

### ISSUE THREAD

**Issue by NormannR** [EconForge/dolang.py#8]
I face an error running the following code

```python
import dolang
from dolang.language import eval_data
data = MappingNode(tag='!Uniform', value=[(ScalarNode(tag='tag:yaml.org,2002:str', value='a'), ScalarNode(tag='tag:yaml.org,2002:str', value='0.98')), (ScalarNode(tag='tag:yaml.org,2002:str', value='b'), ScalarNode(tag='tag:yaml.org,2002:str', value='0.99'))])
eval_data(data)
```
The error code is the following

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/normann/Dropbox/Pablo/dolang.py/dolang/language.py", line 179, in eval_data
    evd = eval_data(ch, calibration=calibration)
  File "/home/normann/Dropbox/Pablo/dolang.py/dolang/language.py", line 145, in eval_data
    sigkeys = [*signature.keys()]
AttributeError: 'NoneType' object has no attribute 'keys'
```

Do you have any clue about that ?

**Comment by NormannR** [comment]
This is actually a dolo.py issue: the distribution object associated with the tag Uniform has no signature. In dolo, adding signature in all distribution.py and processes.py objects solves this issue.
